queue_rules:
  - name: default
    conditions:
      - label=automerge
      - base=master
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"

pull_request_rules:
  - name: auto merge
    conditions:
      - label=automerge
      - base=master
      - "#changes-requested-reviews-by=0"
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
        method: squash

  - name: auto approval
    conditions:
      - author~=^jacogr$
      - label=automerge
    actions:
      review:
        type: APPROVE
        message: This auto-approval rule should be removed once more JS maintainers are active.
