name: Master
on:
  push:
    branches:
      - master

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    strategy:
      matrix:
        step: ['build:release']
    name: ${{ matrix.step }}
    runs-on: ubuntu-latest
    env:
      YARN_ENABLE_SCRIPTS: false
      GH_PAGES_SRC: build
      GH_PAT: ${{ secrets.GH_PAT }}
    steps:
    - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - name: build
      run: |
        yarn install --immutable | grep -v 'YN0013'
        yarn ${{ matrix.step }}
